///////////////////////////////////////////////////////////
//  EventMidAirCol.cs
//  Implementation of the Class EventMidAirCol
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;

namespace SWT_Handin.EventHandling
{
    public class EventMidAirCol : Event
    {
        /// <param name="tracks"></param>
        public override bool CheckEventCond(Tuple<ITrack, ITrack> tracks)
        {
            return false;
        }
    }
} //end EventMidAirCol