///////////////////////////////////////////////////////////
//  ATC.cs
//  Implementation of the Class ATC
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using ATC.Implementation;

namespace SWT_Handin
{
    public class ATC
    {
        public ILog Log;
        private IRenderer _renderer;
        private List<ITrack> _tracks = new List<ITrack>();
        public readonly int AreaHeight;
        public readonly int AreaWidth;
        private int TickTime;
        private int NearMissDist;

        public ATC()
        {
            AreaHeight = 100;
            AreaWidth = 100;
            Log = new ConsolLog();
        }
        /// <param name="track"></param>
        public void AcceptIncomingTrack(ITrack track)
        {
        }

        /// <param name="track"></param>
        public void HandOff(ITrack track)
        {
        }

        public void Tick()
        {
        }
    } //end ATC
} //end namespace Implementation