///////////////////////////////////////////////////////////
//  ConsolLog.cs
//  Implementation of the Class ConsolLog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace SWT_Handin
{
    public class ConsolLog : ILog
    {
        /// <param name="tracks"></param>
        /// <param name="message"></param>
        /// <param name="event"></param>
        public void Log(List<ITrack> tracks, string message)
        {
        }
    } //end ConsolLog
} //end namespace Implementation