///////////////////////////////////////////////////////////
//  ConsolLog.cs
//  Implementation of the Class ConsolLog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace SWT_Handin
{
    public class ConsolLog : ILog
    {
        public void Log(EventMessage message)
        {
            Console.WriteLine("EventType: " + message.EventType);
            Console.WriteLine("Date: {0:dd:MM:yyy}", message.Timestamp);
            Console.WriteLine("Time: {0:hh:mm:ss:fff}", message.Timestamp);
            Console.WriteLine("Involved Tracks:");
            foreach (var track in message.InvolvedTracks)
            {
                Console.WriteLine(track.Tag);
            }
        }
    } //end ConsolLog
} //end namespace Implementation