///////////////////////////////////////////////////////////
//  Event.cs
//  Implementation of the Class Event
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace SWT_Handin
{
    public abstract class Event
    {
        
        /// <param name="tracks"></param>
        public abstract bool CheckEventCond(List<ITrack> tracks);

    }
} //end Event