///////////////////////////////////////////////////////////
//  EventMidAirCol.cs
//  Implementation of the Class EventMidAirCol
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace SWT_Handin.EventHandling
{
    public class EventMidAirCol : IEvent
    {
        /// <param name="tracks"></param>
        private ATC atc;

        public void HookToDetector()
        {
            throw new NotImplementedException();
        }

        public void AttachToAtc(ref ATC airTrafficControl)
        {
            throw new NotImplementedException();
        }

        public void AttachToAtc(ATC airTrafficControl)
        {
            throw new NotImplementedException();
        }

        public bool CheckEventConditions(List<ITrack> tracks)
        {
            throw new NotImplementedException();
        }
    }
} //end EventMidAirCol