///////////////////////////////////////////////////////////
//  IRenderer.cs
//  Implementation of the Interface IRenderer
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace SWT_Handin
{
    public interface ITrackRenderer
    {
        /// <param name="tracks"></param>
        void RenderTracks(List<ITrack> tracks);
    } //end IRenderer
} //end namespace Implementation