///////////////////////////////////////////////////////////
//  FileRenderer.cs
//  Implementation of the Class FileRenderer
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace SWT_Handin
{
    public class TrackRendererFile : ITrackRenderer
    {
        private string _path;

        public TrackRendererFile(string fp)
        {
            _path = fp;
            if (!File.Exists(_path))
            {
                using (FileStream fs = File.Create(fp))
                {
                }
            }
        }


        /// <param name="tracks"></param>
        public void RenderTracks(List<ITrack> tracks)
        {
            var date = DateTime.Now;
            using (var outfile = new StreamWriter(_path, true))
            {
                foreach (var track in tracks)
                {
                    outfile.WriteLine("Time: {0:dd/MM/yyy HH:mm:ss.fff} ", date);
                    outfile.WriteLine("Track: " + track.Tag);
                    String coordinates = "(";
                    foreach (var coord in track.Position.Coordinates)
                    {
                        coordinates += coord +",";
                    }
                    coordinates = coordinates.Remove(coordinates.Length - 1);
                    coordinates += ")";
                    outfile.WriteLine("Coordinates: "+ coordinates);
                    outfile.WriteLine("Direction:");
                    outfile.WriteLine("speed: " + track.Speed);
                    outfile.WriteLine("");
                }
            }
        }
    } //end FileRenderer
} //end namespace Implementation