///////////////////////////////////////////////////////////
//  TwoDTrack.cs
//  Implementation of the Class TwoDTrack
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


namespace SWT_Handin
{
    public class TwoDTrack : ITrack
    {
        public string Tag { get; set; }
        public int Speed { get; set; }
        public IPosition Position { get; set; }
        public Direction TrackDirection { get; set; }

        public void Tick(int tickTime)
        {
            var currentPosition = Position;
            var direction = TrackDirection;
            var speed = Speed;
            switch (direction)
            {
                case Direction.North:
                    Position.Coordinates[1] -= Speed;
                    break;
                case Direction.East:
                    Position.Coordinates[0] += Speed;
                    break;
                case Direction.South:
                    Position.Coordinates[1] += Speed;
                    break;
                case Direction.West:
                    Position.Coordinates[0] -= Speed;
                    break;
            }
        }
    } //end TwoDTrack
} //end namespace Implementation