///////////////////////////////////////////////////////////
//  TwoDTrack.cs
//  Implementation of the Class TwoDTrack
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;

namespace SWT_Handin
{
    public class TwoDTrack : ITrack
    {
        public string Tag { get; set; }
        public int Speed { get; set; }
        public IPosition Position { get; set; }
        public Direction TrackDirection { get; set; }
        private DateTime _lastUpdate = DateTime.Now;
        public void Tick(int tickTime)
        {
            double timeSinceLastUpdate = (DateTime.Now - _lastUpdate).TotalMilliseconds;

            _lastUpdate = DateTime.Now;
            double tomove = (Speed * (tickTime / (double)1000)) + (Speed * ((timeSinceLastUpdate - tickTime) / 1000));
            switch (TrackDirection)
            {
                case Direction.North:
                    Position.Coordinates[1] -= tomove;
                    break;
                case Direction.East:
                    Position.Coordinates[0] += tomove;
                    break;
                case Direction.South:
                    Position.Coordinates[1] += tomove;
                    break;
                case Direction.West:
                    Position.Coordinates[0] -= tomove;
                    break;
            }
        }
    } //end TwoDTrack
} //end namespace Implementation