///////////////////////////////////////////////////////////
//  ATC.cs
//  Implementation of the Class ATC
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using ATC.Implementation;
using SWT_Handin;

namespace SWT_Handin {
	public class ATC {

		private List<ITrack> _tracks = new List<ITrack>();
		private int AreaHeight{ get;  set;} 
		private int AreaWidth{ get;  set;} 
		private int TickTime{ get;  set;} 
		private int NearMissDist{ get;  set;} 
		private IRenderer _renderer;
	    private ILog _log;
		public EventDetector m_EventDetector;


		public ATC(){

		}

		/// 
		/// <param name="track"></param>
		public void AcceptIncomingTrack(ITrack track){

		}

		/// 
		/// <param name="track"></param>
		public void HandOff(ITrack track){

		}

		public void Tick(){

		}

	}//end ATC

}//end namespace Implementation