///////////////////////////////////////////////////////////
//  ConsolLog.cs
//  Implementation of the Class ConsolLog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using ATC.Implementation;
using SWT_Handin;

namespace SWT_Handin {
	public class ConsolLog : ILog {



		~ConsolLog(){

		}

		public ConsolLog(){

		}

		/// 
		/// <param name="event"></param>
        public void Log(List<Tuple<ITrack, ITrack>> events)
        {

		}

	}//end ConsolLog

}//end namespace Implementation