///////////////////////////////////////////////////////////
//  Direction.cs
//  Implementation of the Class Direction
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////




namespace SWT_Handin {
	public enum Direction : int {

		North,
		South,
		East,
		West

	}//end Direction

}//end namespace Implementation