///////////////////////////////////////////////////////////
//  Ilog.cs
//  Implementation of the Interface Ilog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace SWT_Handin {
	public interface ILog  {

		/// 
		/// <param name="events"></param>
		void Log(List<Tuple<ITrack,ITrack>> events);
	}

//end Ilog

}//end namespace Implementation