///////////////////////////////////////////////////////////
//  IPosition.cs
//  Implementation of the Interface IPosition
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;

namespace SWT_Handin {
	public interface IPosition  {
        List<Double> Coordinates{ get;  set;} 
	}//end IPosition

}//end namespace Implementation