///////////////////////////////////////////////////////////
//  IRenderer.cs
//  Implementation of the Interface IRenderer
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using SWT_Handin;

namespace ATC.Implementation {
	public interface IRenderer  {

		/// 
		/// <param name="tracks"></param>
		void RenderTracks(List<ITrack> tracks);
	}//end IRenderer

}//end namespace Implementation