///////////////////////////////////////////////////////////
//  TwoDTrack.cs
//  Implementation of the Class TwoDTrack
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;

namespace SWT_Handin {
	public class TwoDTrack : ITrack {

		public IPosition Position{ get;  set;} 
	    public Direction TrackDirection { get; set; }
	    public int Speed{ get;  set;} 
		public string Tag{ get;  set;} 


		public TwoDTrack(){
		}

	}//end TwoDTrack

}//end namespace Implementation