///////////////////////////////////////////////////////////
//  2dPosition.cs
//  Implementation of the Class 2dPosition
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class 2dPosition : IPosition {

		public List<Double> Coordinates{ get;  set;} 



		~2dPosition(){

		}

		public 2dPosition(){

		}

		/// 
		/// <param name="x"></param>
		/// <param name="y"></param>
		public 2dPosition(double x, double y){

		}

	}//end 2dPosition

}//end namespace Implementation