///////////////////////////////////////////////////////////
//  2dTrackFactory.cs
//  Implementation of the Class 2dTrackFactory
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class 2dTrackFactory : ITrackFactor {

		public 2dTrackFactory(){

		}

		~2dTrackFactory(){

		}

		/// 
		/// <param name="tag"></param>
		/// <param name="speed"></param>
		/// <param name="pos"></param>
		/// <param name="direction"></param>
		public ITrack CreateTrack(string tag, int speed, IPosition pos, Dirention direction){

			return null;
		}

	}//end 2dTrackFactory

}//end namespace Implementation