///////////////////////////////////////////////////////////
//  2dTrack.cs
//  Implementation of the Class 2dTrack
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class 2dTrack : ITrack {

		public IPosition Position{ get;  set;} 
		public Direction Direction{ get;  set;} 
		public int Speed{ get;  set;} 
		public string Tag{ get;  set;} 



		~2dTrack(){

		}

		public 2dTrack(){

		}

	}//end 2dTrack

}//end namespace Implementation