///////////////////////////////////////////////////////////
//  ATC.cs
//  Implementation of the Class ATC
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class ATC {

		private List<ITrack> _tracks = new List<ITrack>;
		private int AreaHeight{ get;  set;} 
		private int AreaWidth{ get;  set;} 
		private int TickTime{ get;  set;} 
		private int NearMissDist{ get;  set;} 
		private IRenderer _renderer;
		public ATC.ATC.Implementation.IRenderer m_IRenderer;
		public EventDetector m_EventDetector;
		public ATC.ATC.Implementation.Ilog m_Ilog;



		~ATC(){

		}

		public ATC(){

		}

		/// 
		/// <param name="track"></param>
		public void AcceptIncomingTrack(ITrack track){

		}

		/// 
		/// <param name="track"></param>
		public void HandOff(ITrack track){

		}

		public void Tick(){

		}

	}//end ATC

}//end namespace Implementation