///////////////////////////////////////////////////////////
//  AtDestinationEvent.cs
//  Implementation of the Class AtDestinationEvent
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




namespace ATC.ATC.Implementation {
	public class AtDestinationEvent : Event {

		public AtDestinationEvent(){

		}

		~AtDestinationEvent(){

		}

	}//end AtDestinationEvent

}//end namespace Implementation