///////////////////////////////////////////////////////////
//  ConsolLog.cs
//  Implementation of the Class ConsolLog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class ConsolLog : Ilog {



		~ConsolLog(){

		}

		public ConsolLog(){

		}

		/// 
		/// <param name="event"></param>
		public void Log(IEvent event){

		}

	}//end ConsolLog

}//end namespace Implementation