///////////////////////////////////////////////////////////
//  Event.cs
//  Implementation of the Class Event
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////




public class Event {

	public Event(){

	}

	~Event(){

	}

	/// 
	/// <param name="tracks"></param>
	public bool CheckEventCond(tuple<ITrack, ITrack> tracks){

		return false;
	}

}//end Event