///////////////////////////////////////////////////////////
//  EventMidAirCol.cs
//  Implementation of the Class EventMidAirCol
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////




public class EventMidAirCol : Event {

	public EventMidAirCol(){

	}

	~EventMidAirCol(){

	}

	/// 
	/// <param name="tracks"></param>
	public override bool CheckEventCond(tuple<ITrack, ITrack> tracks){

		return false;
	}

}//end EventMidAirCol