///////////////////////////////////////////////////////////
//  EventDetector.cs
//  Implementation of the Class EventDetector
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////




public class EventDetector {

	public EventDetector(){

	}

	~EventDetector(){

	}

	/// 
	/// <param name="tracks"></param>
	public List<Tuple<ITrack,ITrack>> DetectEvents(List<Tracks> tracks){

		return null;
	}

}//end EventDetector