///////////////////////////////////////////////////////////
//  FileRenderer.cs
//  Implementation of the Class FileRenderer
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////




using ATC.ATC.Implementation;
namespace ATC.ATC.Implementation {
	public class FileRenderer : IRenderer {

		private string _path;

		public FileRenderer(){

		}

		~FileRenderer(){

		}

		/// 
		/// <param name="fp"></param>
		public FileRenderer(String fp){

		}

		/// 
		/// <param name="tracks"></param>
		public void RenderTracks(List<ITrack> tracks){

		}

	}//end FileRenderer

}//end namespace Implementation