///////////////////////////////////////////////////////////
//  Ilog.cs
//  Implementation of the Interface Ilog
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////




namespace ATC.ATC.Implementation {
	public interface Ilog  {

		/// 
		/// <param name="event"></param>
		void Log(IEvent event);
	}//end Ilog

}//end namespace Implementation