///////////////////////////////////////////////////////////
//  IPosition.cs
//  Implementation of the Interface IPosition
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////




namespace ATC.ATC.Implementation {
	public interface IPosition  {

	}//end IPosition

}//end namespace Implementation