///////////////////////////////////////////////////////////
//  ITrack.cs
//  Implementation of the Interface ITrack
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////




namespace ATC.ATC.Implementation {
	public interface ITrack  {

	}//end ITrack

}//end namespace Implementation