///////////////////////////////////////////////////////////
//  EventDetectorTest.cs
//  Implementation of the Class EventDetectorTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using NSubstitute;
using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class EventHandlerTest
    {
        [Test]
        public void TestDetectEvents_Valid()
        {
            var atc = Substitute.For<ATC>();
            var t1 = new TwoDTrackFactory().CreateTrack("Test", 80, new TwoDPosition(100000, 50), Direction.East);
            var tracklist = new List<ITrack> {t1};
            EventHandler.EventList = new List<IEvent>();

            var myHandle = new EventHandler(ref atc);
            var events = myHandle.DetectEvents(tracklist);
            Assert.True(events.Count > 0);
        }
    } //end EventDetectorTest
} //end namespace UnitTests