///////////////////////////////////////////////////////////
//  EventNearMissTest.cs
//  Implementation of the Class EventNearMissTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using NSubstitute;
using NUnit.Framework;
using SWT_Handin.EventHandling;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class EventNearMissTest
    {
        
        [Test]
        public void CheckEventCond_Valid()
        {
            var atc = Substitute.For<ATC>();
            var t1 = new TwoDTrackFactory().CreateTrack("Test", 80, new TwoDPosition(50, 50), Direction.East);
            var t2 = new TwoDTrackFactory().CreateTrack("Test", 80, new TwoDPosition(2500, 50), Direction.East);
            var tracklist = new List<ITrack> {t1, t2};
            var myHappening = new EventNearMiss();
            myHappening.AttachToAtc(ref atc);
            bool check = myHappening.CheckEventConditions(tracklist);
            Assert.AreEqual(true, check);
        }
    } //end EventNearMissTest
} //end namespace UnitTests