///////////////////////////////////////////////////////////
//  FileRendererTest.cs
//  Implementation of the Class FileRendererTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.IO;
using NSubstitute;
using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class TrackRendererFileTest
    {
        [Test]
        [ExpectedException(typeof(UnauthorizedAccessException))]
        public void Filerenderer_Write_UnautherizedAccesError()
        {
            var fp = @"RendedererAccesError.txt";
            File.Create(fp);
            File.SetAttributes(fp, FileAttributes.ReadOnly);
            var filerenderer = new TrackRendererFile(fp);
            var tl = Substitute.For < List<ITrack>>();
            filerenderer.RenderTracks(tl);
        }

        [Test]
        public void FileRenderer_FileDoesntExist_CreateFile_True()
        {
            var fp = @"RendedererFileDoesntExist.txt";
            if(File.Exists(fp))
                File.Delete(fp);
            var filerenderer = new TrackRendererFile(fp);
            var tl = Substitute.For<List<ITrack>>();
            Assert.True(File.Exists(fp));
        }
        [Test]
        public void RenderTracks_RenderTracks_NoErrors()
        {
            var fp = "RendedererTest.txt";
            /*if(File.Exists(fp))
                File.Delete(fp);
            using (FileStream fs = File.Create(fp))
            {
            }*/
            var filerenderer = new TrackRendererFile(fp);
            var tl = Substitute.For<List<ITrack>>();
            var t1 = Substitute.For<TwoDTrack>();
            var t2 = Substitute.For<TwoDTrack>();
            t1.Position = Substitute.For<TwoDPosition>(0,0);
            t2.Position = Substitute.For<TwoDPosition>(0, 0);
            tl.Add(t1);
            tl.Add(t2);
            filerenderer.RenderTracks(tl);
        }
    } //end FileRendererTest
} //end namespace UnitTests