///////////////////////////////////////////////////////////
//  TwoDTrackTest.cs
//  Implementation of the Class TwoDTrackTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using NSubstitute;
using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class TwoDTrackTest
    {
        [Test]
        public void PropertySpeed_SetAndGet_True()
        {
            var testTrack = new TwoDTrack {Speed = 100};
            Assert.AreEqual(100, testTrack.Speed);
        }
        [Test]
        public void PropertyTag_SetAndGet_True()
        {
            var testTrack = new TwoDTrack {Tag = "TestTag!"};
            Assert.AreEqual("TestTag!", testTrack.Tag);
        }

        [Test]
        public void PropertyPosition_SetAndGet_True()
        {
            var position = Substitute.For<IPosition>();
            var testTrack = new TwoDTrack {Position = position};
            Assert.AreEqual(position, testTrack.Position);
        }
    } //end TwoDTrackTest
} //end namespace UnitTests