///////////////////////////////////////////////////////////
//  TwoDPositionTest.cs
//  Implementation of the Class TwoDPositionTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class TwoDPositionTest
    {
        [Test]
        public void PropertyCoordinates_SetAndGet_True()
        {
            var testPosition = new TwoDPosition(20.134, 15.2);
            var coords = new List<double> {1.2, 2.3};
            testPosition.Coordinates = coords;
            Assert.AreEqual(coords, testPosition.Coordinates);
        }

        [Test]
        [ExpectedException(typeof (Exception))]
        public void PropertyCoordinates_Set_WrongDimension()
        {
            var testPosition = new TwoDPosition(20.134, 15.2);
            var coords = new List<double> {1.2, 2.3, 2.6};
            testPosition.Coordinates = coords;
        }
    } //end TwoDPositionTest
} //end namespace UnitTests