///////////////////////////////////////////////////////////
//  ATCTest.cs
//  Implementation of the Class ATCTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class ATCTest
    {
        [SetUp]
        protected void SetUp()
        {
        }

        [Test]
        public void TestAcceptIncomingTrack()
        {
        }

        [Test]
        public void TestHandOff()
        {
        }

        [Test]
        public void TestTick()
        {
        }

        [Test]
        public void testATC()
        {
        }
    } //end ATCTest
} //end namespace UnitTests