///////////////////////////////////////////////////////////
//  EventMidAirColTest.cs
//  Implementation of the Class EventMidAirColTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class EventMidAirColTest
    {
        [SetUp]
        protected void SetUp()
        {
        }

        [Test]
        public void TestCheckEventCond()
        {
        }
    } //end EventMidAirColTest
} //end namespace UnitTests