///////////////////////////////////////////////////////////
//  TwoDTrackFactoryTest.cs
//  Implementation of the Class TwoDTrackFactoryTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit {
	[TestFixture]
	public class TwoDTrackFactoryTest {

		public TwoDTrackFactoryTest(){

		}

		~TwoDTrackFactoryTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testCreateTrack(){

		}

	}//end TwoDTrackFactoryTest

}//end namespace UnitTests