///////////////////////////////////////////////////////////
//  TwoDPositionTest.cs
//  Implementation of the Class TwoDPositionTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class TwoDPositionTest
    {
        [SetUp]
        protected void SetUp()
        {
        }

        [Test]
        public void TestTwoDPosition()
        {
        }

        [Test]
        public void TestTwoDPositiondoubledouble()
        {
        }
    } //end TwoDPositionTest
} //end namespace UnitTests