///////////////////////////////////////////////////////////
//  TwoDTrackTest.cs
//  Implementation of the Class TwoDTrackTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit {
	[TestFixture]
	public class TwoDTrackTest {

		public TwoDTrackTest(){

		}


		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testTwoDTrack(){

		}

	}//end TwoDTrackTest

}//end namespace UnitTests