///////////////////////////////////////////////////////////
//  EventNearMiss.cs
//  Implementation of the Class EventNearMiss
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;

namespace SWT_Handin.EventHandling
{
    public class EventNearMiss : Event {

        public EventNearMiss(){

        }

        ~EventNearMiss(){

        }

        /// 
        /// <param name="tracks"></param>
        public override bool CheckEventCond(Tuple<ITrack, ITrack> tracks){

            return false;
        }

    }
}//end EventNearMiss