///////////////////////////////////////////////////////////
//  2dPositionTest.cs
//  Implementation of the Class 2dPositionTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class 2dPositionTest {

		public 2dPositionTest(){

		}

		~2dPositionTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void test2dPosition(){

		}

		[Test]
		public void test2dPositiondoubledouble(){

		}

	}//end 2dPositionTest

}//end namespace UnitTests