///////////////////////////////////////////////////////////
//  2dTrackFactoryTest.cs
//  Implementation of the Class 2dTrackFactoryTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class 2dTrackFactoryTest {

		public 2dTrackFactoryTest(){

		}

		~2dTrackFactoryTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testCreateTrack(){

		}

	}//end 2dTrackFactoryTest

}//end namespace UnitTests