///////////////////////////////////////////////////////////
//  2dTrackTest.cs
//  Implementation of the Class 2dTrackTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class 2dTrackTest {

		public 2dTrackTest(){

		}

		~2dTrackTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void test2dTrack(){

		}

	}//end 2dTrackTest

}//end namespace UnitTests