///////////////////////////////////////////////////////////
//  ATCTest.cs
//  Implementation of the Class ATCTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class ATCTest {

		public ATCTest(){

		}

		~ATCTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testATC(){

		}

		[Test]
		public void testAcceptIncomingTrack(){

		}

		[Test]
		public void testHandOff(){

		}

		[Test]
		public void testTick(){

		}

	}//end ATCTest

}//end namespace UnitTests