///////////////////////////////////////////////////////////
//  AtDestinationEventTest.cs
//  Implementation of the Class AtDestinationEventTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class AtDestinationEventTest {

		public AtDestinationEventTest(){

		}

		~AtDestinationEventTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

	}//end AtDestinationEventTest

}//end namespace UnitTests