///////////////////////////////////////////////////////////
//  ConsolLogTest.cs
//  Implementation of the Class ConsolLogTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class ConsolLogTest {

		public ConsolLogTest(){

		}

		~ConsolLogTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testConsolLog(){

		}

		[Test]
		public void testLog(){

		}

	}//end ConsolLogTest

}//end namespace UnitTests