///////////////////////////////////////////////////////////
//  DirectionTest.cs
//  Implementation of the Class DirectionTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class DirectionTest {

		public DirectionTest(){

		}

		~DirectionTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

	}//end DirectionTest

}//end namespace UnitTests