///////////////////////////////////////////////////////////
//  EventNearMissTest.cs
//  Implementation of the Class EventNearMissTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class EventNearMissTest {

		public EventNearMissTest(){

		}

		~EventNearMissTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testCheckEventCond(){

		}

	}//end EventNearMissTest

}//end namespace UnitTests