///////////////////////////////////////////////////////////
//  EventMidAirColTest.cs
//  Implementation of the Class EventMidAirColTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class EventMidAirColTest {

		public EventMidAirColTest(){

		}

		~EventMidAirColTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testCheckEventCond(){

		}

	}//end EventMidAirColTest

}//end namespace UnitTests