///////////////////////////////////////////////////////////
//  EventAtDestinationTest.cs
//  Implementation of the Class EventAtDestinationTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class EventAtDestinationTest {

		public EventAtDestinationTest(){

		}

		~EventAtDestinationTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testCheckEventCond(){

		}

	}//end EventAtDestinationTest

}//end namespace UnitTests