///////////////////////////////////////////////////////////
//  FileRendererTest.cs
//  Implementation of the Class FileRendererTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////




using NUnit.Framework;
using ATC.ATC.Implementation;
namespace ATC.ATC.UnitTests {
	[TestFixture]
	public class FileRendererTest {

		public FileRendererTest(){

		}

		~FileRendererTest(){

		}

		[SetUp]
		protected void SetUp(){

		}

		[Test]
		public void testFileRenderer(){

		}

		[Test]
		public void testRenderTracks(){

		}

	}//end FileRendererTest

}//end namespace UnitTests