///////////////////////////////////////////////////////////
//  ConsolLogTest.cs
//  Implementation of the Class ConsolLogTest
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:50
//  Original author: Pierre
///////////////////////////////////////////////////////////


using NUnit.Framework;

namespace SWT_Handin.Tests.Unit
{
    [TestFixture]
    public class ConsolLogTest
    {
        [SetUp]
        protected void SetUp()
        {
        }

        [Test]
        public void TestConsolLog()
        {
        }

        [Test]
        public void TestLog()
        {
        }
    } //end ConsolLogTest
} //end namespace UnitTests