///////////////////////////////////////////////////////////
//  ATC.cs
//  Implementation of the Class ATC
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using ATC.Implementation;

namespace SWT_Handin
{
    public class ATC
    {
        private ILog _log;
        private IRenderer _renderer;
        private List<ITrack> _tracks = new List<ITrack>();
        public EventDetector m_EventDetector;
        private int AreaHeight { get; set; }
        private int AreaWidth { get; set; }
        private int TickTime { get; set; }
        private int NearMissDist { get; set; }


        /// <param name="track"></param>
        public void AcceptIncomingTrack(ITrack track)
        {
        }

        /// <param name="track"></param>
        public void HandOff(ITrack track)
        {
        }

        public void Tick()
        {
        }
    } //end ATC
} //end namespace Implementation