///////////////////////////////////////////////////////////
//  EventDetector.cs
//  Implementation of the Class EventDetector
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:26:32
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using SWT_Handin;

public class EventDetector
{
    /// <param name="tracks"></param>
    public List<Tuple<ITrack, ITrack>> DetectEvents(List<ITrack> tracks)
    {
        return null;
    }
} //end EventDetector