///////////////////////////////////////////////////////////
//  ITrackFactor.cs
//  Implementation of the Interface ITrackFactor
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:57
//  Original author: Pierre
///////////////////////////////////////////////////////////


namespace SWT_Handin
{
    public interface ITrackFactor
    {
        /// <param name="tag"></param>
        /// <param name="speed"></param>
        /// <param name="pos"></param>
        /// <param name="direction"></param>
        ITrack CreateTrack(string tag, int speed, IPosition pos, Direction direction);
    } //end ITrackFactor
} //end namespace Implementation