///////////////////////////////////////////////////////////
//  TwoDPosition.cs
//  Implementation of the Class TwoDPosition
//  Generated by Enterprise Architect
//  Created on:      18-jun-2014 01:25:56
//  Original author: Pierre
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace SWT_Handin
{
    public class TwoDPosition : IPosition
    {
        public TwoDPosition()
        {
        }

        /// <param name="x"></param>
        /// <param name="y"></param>
        public TwoDPosition(double x, double y)
        {
        }

        public List<Double> Coordinates { get; set; }
    } //end TwoDPosition
} //end namespace Implementation